language: cpp

compiler:
- gcc

os:
- linux
ruby: 2.2.0

before_install:
- echo $LANG
- echo $LC_ALL

script: make run


branches:
  only:
  - master

notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#rubinius
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      secure: h2oTAbAZF6+c6iv/kHoDGtl1mzQDF2vQSKWnO1pwfEz+L80lX9u3+JB+jsbYUcZ9smBRnRRghqxpLBmyzH3QZCrBdxKnTWfGc7I7lkTCFQZ5O3pPmIusO6W5zX+YUc+NHPPZXouHuHFmEeEB9vJnt/YB/fyGAGOIq+qXV4s+R9M=
    on_success: always
    on_failure: always
    on_start: always
env:
  global:
  - OPENSSL_DIR=$(brew --prefix openssl)
  - RBXOPT=-Xcodedb.cache.enabled=no
  - LANG="en_US.UTF-8"

